name: ishmael
favicon: null
layout_spectrum: 0.6393847872968763
typography_spectrum: 0.9404233526438475
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.8480425267480314
  lightness: 0.37881139176897705
  saturation: 0.9871920647565275
  rhythmicContrast: 0.0067904016468673944
purpose: []
